export const MAIN_WINDOW_ACTIONS = {
	OPEN_LOGIN_WINDOW: "@IPC_MAIN_WINDOW/OPEN_LOGIN_WINDOW",
	AUTHENTICATED: "@IPC_MAIN/AUTHENTICATED",
};

export const LOGIN_WINDOW_ACTIONS = {
	SUBMIT: "@IPC_LOGIN_WINDOW/SUBMIT",
};
