export const MAIN_WINDOW_ACTIONS = {
	OPEN_LOGIN_WINDOW: "@IPC_MAIN_WINDOW/OPEN_LOGIN_WINDOW",
	AUTHENTICATED: "@IPC_MAIN/AUTHENTICATED",
	LOGOUT: "@IPC_MAIN_WINDOW/LOGOUT",
	CLOSE: "@IPC_MAIN_WINDOW/CLOSE",
};

export const LOGIN_WINDOW_ACTIONS = {
	SUBMIT: "@IPC_LOGIN_WINDOW/SUBMIT",
};
